version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /mars/JointGenotypingTasksMars.wdl
    readMePath: /mars/README.md
    testParameterFiles:
    name: JointGenotypingTasksMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: joint genotyping tasks for import into joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: /mars/JointGenotypingMars.wdl
    readMePath: /mars/README.md
    testParameterFiles:
    name: JointGenotypingMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: main joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: /mars/JointVcfFilteringMars.wdl
    readMePath: /mars/README.md
    testParameterFiles:
    name: JointVcfFilteringMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: vcf filtering tasks for import into joint genotyping workflow
