version: 1.2
workflows:
    subclass: WDL
    primaryDescriptorPath: /mars/JointGenotypingTasks_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
    
    subclass: WDL
    primaryDescriptorPath: /mars/JointGenotyping_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
        
    subclass: WDL
    primaryDescriptorPath: /mars/JointVcfFiltering_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
