version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: https://github.com/mewhitebroad/mars/JointGenotypingTasksMars.wdl
    readMePath: https://github.com/mewhitebroad/mars/README.md
    testParameterFiles:
    name: JointGenotypingTasksMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: joint genotyping tasks for import into joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: https://github.com/mewhitebroad/mars/JointGenotypingMars.wdl
    readMePath: https://github.com/mewhitebroad/mars/README.md
    testParameterFiles:
    name: JointGenotypingMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: main joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: https://github.com/mewhitebroad/mars/JointVcfFilteringMars.wdl
    readMePath: https://github.com/mewhitebroad/mars/README.md
    testParameterFiles:
    name: JointVcfFilteringMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: vcf filtering tasks for import into joint genotyping workflow
