  version: 1.0
  
  workflows:
    name: JointGenotypingTasks_mars.wdl
    subclass: WDL
    primaryDescriptorPath: /mars/JointGenotypingTasks_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
    
    name: JointGenotyping_mars.wdl
    subclass: WDL
    primaryDescriptorPath: /mars/JointGenotyping_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
        
    name: JointVcfFiltering_mars.wdl
    subclass: WDL
    primaryDescriptorPath: /mars/JointVcfFiltering_mars.wdl
    readMePath: /mars/README.md
    authors:
      - name: Michelle White
        email: mwhite@broadinstitute.org
