version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: ./JointGenotypingTasksMars.wdl
    readMePath: ./README.md
    testParameterFiles:
    name: JointGenotypingTasksMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: joint genotyping tasks for import into joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: ./JointGenotypingMars.wdl
    readMePath: ./README.md
    testParameterFiles:
    name: JointGenotypingMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: main joint genotyping workflow
  - subclass: WDL
    primaryDescriptorPath: ./JointVcfFilteringMars.wdl
    readMePath: ./README.md
    testParameterFiles:
    name: JointVcfFilteringMars
    authors:
     - name: Michelle White
       email: mwhite@broadinstitute.org
    topic: vcf filtering tasks for import into joint genotyping workflow
